### ISSUE TITLE
How to use in browser with vanilla JS? CJS - import issue, ESM - 403 forbidden

### ISSUE THREAD

**Issue by kinguru** [koblas/stdnum-js#123]
Dear David,
could you please help on how to use the module in the plain-text javascript page?
My page is:
![image](https://github.com/user-attachments/assets/ded7d9ed-4008-4ce1-91bc-4bd18f1d6690)

The error I get in browser console is:
![image](https://github.com/user-attachments/assets/b034e09d-e558-4381-a30a-c405f1c8922c)

If I use ESM build, then the result in browser console is:
![image](https://github.com/user-attachments/assets/776348ff-5dd1-4f88-ad94-722d7c63890f)

Please help with the module usage.
Thanks in advance and have a good day.

**Comment by koblas** [comment]
This package should be use in conjunction with a bundler, like esbuild or web pack to create browser compatible assets.

**Comment by kinguru** [comment]
I've created a bundle with esbuild, like:
`.\node_modules\.bin\esbuild lib\esm\index.js --bundle --sourcemap --target=chrome58 > stdnum.esm.js`

Than included the resulting file in the index.html like:
`<script src="stdnum.esm.js"></script>`

No errors in console, so file is loaded fine. 
But how to use the stdnum APIs? The "stdnum" variable is not defined...
Sorry for stupid questions.
