### ISSUE TITLE
False positives for Netherlands / BSN that are too short

### ISSUE THREAD

**Issue by mikeryancodes** [koblas/stdnum-js#17]
Sample code producing the error:

```javascript
const { stdnum } = require('stdnum');
const { bsn } = stdnum.NL;
bsn.validate('1').isValid; // true, should be false
```
It looks like `validate` is converting `value` to a string padded with 0s up to a length of 9 via `clean` before doing the length check, the length will always be 9 due to the padding.

**Comment by mikeryancodes** [comment]
This also appears in `onderwijsnummer`, though that winds up getting caught by a format check for the first two digits. Still, I think we would want to see it fail a length check.

**Comment by koblas** [comment]
This is now resolved, closing.
