### ISSUE TITLE
Belgium: BE VAT 417497106

### ISSUE THREAD

**Issue by AlexeyKhmelev** [koblas/stdnum-js#28]
Hey team!

I've tried Belgium VAT number 0417497106, which returns false for checksum. But it's an actual number. Could you please help me with that?

**Comment by AlexeyKhmelev** [comment]
Maybe the fix should be like that:

<img width="679" alt="Screen Shot 2022-07-27 at 10 20 25" src="https://user-images.githubusercontent.com/22537517/181153516-b99b369e-5468-42b0-a29c-6dca43d1e288.png">

**Comment by koblas** [comment]
Always open to pull requests as well.  The fix you outlined is good.
