### ISSUE TITLE
German National ID number (Personalausweisnummer)

### ISSUE THREAD

**Issue by teebu** [koblas/stdnum-js#43]
Can you add DE Personalausweisnummer
regex: `^[lmnprtvwxy][0-9cfghjklmnprtvwxyz]{8}[0-9][d]?`

some Refs:
http://www.pruefziffernberechnung.de/P/Personalausweis-DE.shtml
https://learn.microsoft.com/en-us/microsoft-365/compliance/sit-defn-germany-identity-card-number?view=o365-worldwide
https://www.php-einfach.de/diverses/personalausweis-ueberpruefen/

It's alpha char convert to digit (if present) and a repeating weight of 7,3,1 and the check digit is last digit, sometimes has optional 'D' in the value in the end.

```
First, the letters are converted into numbers. An A becomes 10, a B becomes 11, and so on.
Then each digit is multiplied by a value.
The first digit is multiplied by the value 7, the second by the value 3, and the third digit by the value 1. Then this sequence starts over.
The check digit is then the last digit of the sum over the previous multiplications.
```

**Comment by koblas** [comment]
Should now be available -> PR #45 should add it.

**Comment by teebu** [comment]
I can't find any site talking about the length of Personalausweisnummer as being 24. 

Can you add tests for the old format. 

```
    '2406055684',
    '2406055684d',
    '2406055684 D',
    'T220001293D',
    'T220001293',
    'L01X00T471'
```

https://github.com/koblas/stdnum-js/blob/1b1933e79e9d1703dad8e423b27805a1dbb385b0/src/de/pwnr.spec.ts

**Comment by koblas** [comment]
PR #48 should resolve all of these issues, please review and let me know.

**Comment by teebu** [comment]
Looks good, I have yet to find documentation on the "new" 26 length format, because the "new" and current format is the 11, in the German person I talked to. The previous one didn't have letters, as Microsoft points out.

Can you point me where you found it?

**Comment by koblas** [comment]
The first set of numbers is a combination of the issuing agency and a sequence number. If you review the list most of these are numeric, but it looks like most of the E-Pass (whatever that is, have alphanumeric coding)

http://www.pruefziffernberechnung.de/Begleitdokumente/BKZ.shtml

**Comment by teebu** [comment]
I think I see now, its found here http://www.pruefziffernberechnung.de/R/Reisepass-DE.shtml 

The 11 digits + dob + some other numbers = 26 chars
