### ISSUE TITLE
Mexico CURP might need minor corrections

### ISSUE THREAD

**Issue by teebu** [koblas/stdnum-js#44]
Taken from: https://en.wikipedia.org/wiki/Unique_Population_Registry_Code
If any step in the above procedure leads to the letter "[Ñ](https://en.wikipedia.org/wiki/%C3%91)" appearing anywhere in the CURP, the "Ñ" is replaced by an "X".

A one-letter gender indicator (H for male (hombre in Spanish), M for female (mujer in Spanish), or X for non-binary); [[1]](https://en.wikipedia.org/wiki/Unique_Population_Registry_Code#cite_note-1)

However, I can't seem to find official documentation for this.

**Comment by teebu** [comment]
Ok, how about the non-binary X?

**Comment by koblas** [comment]
Similar statements would apply.  Since the CURP is the encoding of these fields as long as it was originally encoded correctly there should be no issue with validating the CURP.  

That said, reviewing the code `getGender()` will return the wrong gender for 'X'.
