### ISSUE TITLE
France INSEE or NIR validation issue

### ISSUE THREAD

**Issue by teebu** [koblas/stdnum-js#52]
Using online tool: https://randommer.io/SocialNumber/SsnValidator

I referenced this python code as a source:
https://gist.github.com/jauneau/1206760

number: `186022A21532523`
result: Valid

![image](https://github.com/koblas/stdnum-js/assets/5531844/40bc0b86-b6cf-4877-a04a-8823723eff9f)

The library returns invalid.

Other numbers tested and passed validation:
`169109935247001`
`178059933010817`
`2820417379785 16`

**Comment by koblas** [comment]
Good find.
