### ISSUE TITLE
France NIF / TIN checksum missing

### ISSUE THREAD

**Issue by teebu** [koblas/stdnum-js#55]
France, the terms "TIN" (Tax Identification Number) and "NIF" (Numéro d'Identification Fiscale) are used interchangeably and refer to the same thing. The French NIF is the unique identifier assigned to individuals and legal entities for tax purposes, and it serves as the TIN for tax-related matters in France.

https://ec.europa.eu/taxation_customs/tin/specs/FS-TIN%20Algorithms-Public.docx

![image](https://github.com/koblas/stdnum-js/assets/5531844/e7b19793-07c4-479e-aa87-fc29be87fa7c)

**Comment by koblas** [comment]
Unless I missed something `0000000000000` is a valid checksum.  Since 0 mod 511 = 0.

Though it would be great to see a rule that clarifies this:

> Check digit = remainder if remainder < 100, C11 = 0 (if remainder < 10, C11 = 0 and C12 = 0).

Since this implies that if the number is `0000000001000` it's valid -- IMHO this is strange for a bunch of reasons.

**Comment by teebu** [comment]
Even though it is valid checksum, and probably the same for most of these mod based checksums. I think it should make it invalid.
