### ISSUE TITLE
Bug with Germany(DE)  stnr validation

### ISSUE THREAD

**Issue by olehAndersen** [koblas/stdnum-js#7]
Hi!
Found a bug when validating _Steuernummer, German tax number_ `stnr` most examples from the [wiki](https://de.wikipedia.org/wiki/Steuernummer)  fail validation and return an error 
<img width="817" alt="Tax number - Wikipedia 2022-04-25 19-49-04" src="https://user-images.githubusercontent.com/100132963/165136626-61d5bbf0-4389-425f-af6c-b03479578447.png">
Although the library that you inspired [python-stdnum](https://arthurdejong.org/python-stdnum/) validates these numbers correctly
 i.e.
`stnr.validate('18181508155')`
or
`stnr.validate('181/815/0815 5') `
result will be
<img width="1619" alt="Wayflyer (dev) - Verify your business 2022-04-25 19-56-49" src="https://user-images.githubusercontent.com/100132963/165137162-1b385a10-9222-43f9-95a6-460115fd322f.png">

**Comment by koblas** [comment]
Thanks for the report!   I'll hopefully get to this in the next day or two.

**Comment by koblas** [comment]
Digging into this, I think the wikipedia page does not have valid Stnr values.  There are two validation criteria for Steuernummers.

* In the first 10 digits exactly one digit must be repeated two or three times and other digits can appear only once.
* The check digits are failing as well

When I look at these numbers carefully I note that they all consist of similar repeating patterns that probably are not valid. Can you please confirm that these should be valid numbers and not just examples.

**Comment by koblas** [comment]
For reference, the python stdnum package only does syntactical validation no checksum validation.

**Comment by olehAndersen** [comment]
Thanks for the quick response  🚀
I'm trying to find confirmation on real Steuernummer, this takes time. I will try until the end of the week. The confusing thing is that all validators give the same result, but stdnum-js is different. Give me some time to check the data please. This issue is useful in any case 🙂

**Comment by olehAndersen** [comment]
Hi guys!
I tried using and validating an existing number `121/5752/5373` and it also failed checksum validation.
Any chance I can have a check this, please?

<img width="1159" alt="Slack | Darren Burke, Mark Butcher | Wayflyer 2022-05-03 16-50-49" src="https://user-images.githubusercontent.com/100132963/166465843-ffdba86a-abf6-4a4f-a5bd-501f63b77b3a.png">
