### ISSUE TITLE
Swiss SSN validation (EAN) checksum issue

### ISSUE THREAD

**Issue by teebu** [koblas/stdnum-js#94]
value: 756.9203.3850.60
expected result: valid

also checked here: 
https://teaddict.net/swiss-ssn.html
https://www.getnewidentity.com/validate-ean.php (value without periods)

I think we seen this mod 10 = 0 issue in before in another validator. `(10 - sum) % 10)` ?

**Comment by koblas** [comment]
Good catch, that was the issue.
